---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  flavor_id: <%= ENV['EC2_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: amazon-2014.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-9a6ed3f2
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

- name: amazon-2015.03
  driver_plugin: ec2
  driver_config:
    image_id: ami-0d4cfd66
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]
