driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-10.04
  run_list:
    - recipe[packagecloud_test::lucid_deps]
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems_private]

- name: ubuntu-12.04
  run_list:
    - recipe[packagecloud_test::precise_deps]
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems_private]

- name: ubuntu-14.04
  run_list:
    - recipe[packagecloud_test::trusty_deps]
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems]

- name: centos-5-11-without-epel
  driver:
        box: opscode-centos-5.11
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

- name: centos-5.11-with-epel
  driver:
        box: opscode-centos-5.11
  run_list:
    - recipe[packagecloud_test::epel5]
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems_private]

- name: centos-6.7
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

- name: centos-7.1
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems_private]

- name: amazon-2014.09
  driver_name: ec2
  driver_config:
    image_id: ami-b5a7ea85
    username: ec2-user
    aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
    ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
    availability_zone: us-west-2a
    region: us-west-2
    flavor_id: t2.micro
    security_group_ids: sg-598e583c
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

suites:
- name: default
  run_list:
  attributes: {}
