---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-10.04
  run_list:
    - recipe[packagecloud_test::lucid_deps]
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems_private]

- name: ubuntu-12.04
  run_list:
    - recipe[packagecloud_test::precise_deps]
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems_private]

- name: ubuntu-14.04
  run_list:
    - recipe[packagecloud_test::trusty_deps]
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems]

- name: centos-without-epel-5.11
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

- name: centos-with-epel-5.11
  run_list:
    - recipe[packagecloud_test::epel5]
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems_private]

- name: centos-6.7
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

- name: centos-7.1
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems_private]

suites:
- name: default
  run_list:
  attributes: {}
